name: Daily Scrape
description: Scrape yesterday's Registerbekanntmachungen daily at 4 am UTC and store to /db/ folder.

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # Run at 4 am UTC

permissions:
  contents: write  # Allow push access to the repository

jobs:
  scrape-and-commit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq libnss3 wget unzip
          gem install bundler
          bundle install

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y -qq ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Scraper for yesterday in verbose (and headless mode)
        run: |
          bundle exec ruby lib/registerbekanntmachungen.rb -y -v

      - name: Commit Scraper Output
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add db/
          git commit -m "Automated update: Scraper results for $(date -d "yesterday" +%Y-%m-%d)"
          git push

  build-and-deploy:
    needs: scrape-and-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use a recent LTS version

      - name: Install build dependencies
        run: npm install fuse.js

      - name: Pre-build search data and manifest
        run: node scripts/build-index.js

      - name: Copy raw data files for on-demand loading
        run: cp -r db public/db

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The directory to publish
          publish_dir: ./public
          # The branch to deploy to
          publish_branch: gh-pages
          # Create a clean history for each deployment
          force_orphan: true